name: build-test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # (옵션) 히스토리 필요한 경우만

      - name: Debug workspace
        run: |
          pwd
          ls -la
          test -f package.json && echo "package.json FOUND" || (echo "package.json MISSING" && exit 1)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # 테스트가 있으면 활성화
      # - name: Test
      #   run: npm test -- --ci
